# Generated by Django 4.2.20 on 2025-04-04 13:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLMatcherJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('csv_file', models.FileField(upload_to='csv_uploads/')),
                ('similarity_threshold', models.FloatField(default=0.7)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('summary_file', models.CharField(blank=True, max_length=255, null=True)),
                ('results_file', models.CharField(blank=True, max_length=255, null=True)),
                ('exact_matches_file', models.CharField(blank=True, max_length=255, null=True)),
                ('partial_matches_file', models.CharField(blank=True, max_length=255, null=True)),
                ('unmatched_live_file', models.CharField(blank=True, max_length=255, null=True)),
                ('unmatched_staging_file', models.CharField(blank=True, max_length=255, null=True)),
                ('total_urls', models.IntegerField(default=0)),
                ('exact_matches', models.IntegerField(default=0)),
                ('partial_matches', models.IntegerField(default=0)),
                ('unmatched_live', models.IntegerField(default=0)),
                ('unmatched_staging', models.IntegerField(default=0)),
            ],
        ),
    ]
